external_components:
  - source: 
      type: local
      path: ./components

esphome:
  name: esp-spa
  friendly_name: esp-spa
  platformio_options:
    board_build.flash_mode: dio
    board_build.extra_flags: []

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

uart:
  id: spa_uart_bus
  tx_pin: GPIO21
  rx_pin: GPIO20
  data_bits: 8
  parity: NONE
  stop_bits: 1
  baud_rate: 115200

climate:
  - platform: balboa_spa
    name: "My Spa"
    balboa_spa_id: balboa_spa_id

button:
  - platform: balboa_spa
    name: "Lights Toggle"
    button_datapoint: 0
  - platform: balboa_spa
    name: "Jet1 Toggle"
    button_datapoint: 1
    icon: "mdi:fan"
  - platform: balboa_spa
    name: "Jet2 Toggle"
    button_datapoint: 2
    icon: "mdi:fan"
  
binary_sensor:
  - platform: balboa_spa
    name: "Lights"
    binary_sensor_datapoint: 20
  - platform: balboa_spa
    name: "Heater"
    binary_sensor_datapoint: 21
  - platform: balboa_spa
    name: "Circulation Pump"
    binary_sensor_datapoint: 22
  - platform: balboa_spa
    name: "Rest"
    binary_sensor_datapoint: 23
  - platform: balboa_spa
    name: "Jet1"
    binary_sensor_datapoint: 24
  - platform: balboa_spa
    name: "Jet2"
    binary_sensor_datapoint: 25
  - platform: balboa_spa
    name: "Blower"
    binary_sensor_datapoint: 26

balboa_spa:
  id: balboa_spa_id
  uart_id: spa_uart_bus
  fault_text_sensor:
    name: "Fault Message"
  hour_sensor:
    name: "Spa Hour"
  minute_sensor:
    name: "Spa Minute"
  

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  use_address: !secret spa_address
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Spa Fallback Hotspot"
    password: a123123123123

  output_power: 8.5dB
captive_portal:
    